apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-openshift-machineconfig-master-console
spec:
  kernelArguments:
  - console=hvc0 
  - console=ttyS0

