version: "1.0.0"
variant: fcos
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQ-sample
systemd:
  units:
   - name: podman.socket
     enabled: true
storage:
  # Ignition has a bug/feature? where if you make a series of dirs
  # in one swoop, then the leading dirs are creates as root.
  directories:
    - path: /home/core/.config
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/containers
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd/user
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd/user/default.target.wants
      user:
        name: core
      group:
        name: core
  links:
    - path: /home/core/.config/systemd/user/default.target.wants/podman.socket
      user:
        name: core
      group:
        name: core
      target: /usr/lib/systemd/user/podman.socket
      hard: false
  files:
    - path: /var/lib/systemd/linger/core
      mode: 0644
    - path: /usr/local/share/cockpit/shell/manifest.json
      mode: 0644
      contents:
        inline: |
         {
             "requires": {
                 "cockpit": "137"
             },
             "tools": {
                 "index": {
                     "label": "system"
                 }
             }
         }
    - path: /usr/local/share/cockpit/shell/index.html
      mode: 0644
      contents:
        inline: |
         <html>
           <body>
              <meta http-equiv="refresh" content="0; url=/cockpit/@localhost/podman/index.html#">
           </body>
         </html>
