apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    # token max age set to 365 days
    accessTokenMaxAgeSeconds: 31536000
  identityProviders:
  - name: developer
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret 
