apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crc-image-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: crc-csi-hostpath-provisioner
