apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      volume: "pv0001"
