resources:
  - csi-kubevirt-hostpath-provisioner.yaml
images:
  - name: quay.io/kubevirt/hostpath-csi-driver
    newName: registry.redhat.io/container-native-virtualization/hostpath-csi-driver-rhel8
    newTag: v4.11.0
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newName: registry.redhat.io/openshift4/ose-csi-node-driver-registrar
    newTag: latest
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newName: registry.redhat.io/openshift4/ose-csi-livenessprobe
    newTag: latest
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newName: registry.redhat.io/openshift4/ose-csi-external-provisioner
    newTag: latest
